typedef enum _SchroWaveletIndex {
  SCHRO_WAVELET_DESL_9_3,
  SCHRO_WAVELET_5_3,
  SCHRO_WAVELET_13_5,
  SCHRO_WAVELET_HAAR_0,
  SCHRO_WAVELET_HAAR_1,
  SCHRO_WAVELET_HAAR_2,
  SCHRO_WAVELET_FIDELITY,
  SCHRO_WAVELET_DAUB_9_7
} SchroWaveletIndex;
